#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry "debian-10.13.0-i386-netinst.iso"{
	insmod ext2
	set isofile="/boot/customiso/debian-10.13.0-i386-netinst.iso"
	loopback loop (hd0,msdos1)$isofile
	linux (loop)/casper/vmlinuz boot=live iso-scan/filename=$isofile quiet noeject noprompt splash
	initrd (loop)/casper/initrd
}
