#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "ubuntu-18.04.6-live-server-amd64.iso" {
insmod ext2
  set isofile="/boot/customiso/ubuntu-18.04.6-live-server-amd64.iso"
  loopback loop (hd0,msdos1)$isofile
  linux (loop)/casper/vmlinuz boot=casper iso-scan/filename=$isofile noprompt noeject toram
  initrd (loop)/casper/initrd
}
